name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions π€
on: [pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name:"1.Checkout"
      uses:""
    

     run: echo "π‰ The job was automatically triggered by a ${{ github.event_name }} event."
      # code λ³µμ‚¬(action), node.js ν™κ²½ μ„Έν…, build, test

